# Stage 1: Build the Vue.js application
FROM node:20-alpine AS builder

WORKDIR /app/client

COPY ../package.json ../
COPY package.json ./

RUN npm install -g pnpm && \
    pnpm install ../ && \
    pnpm install

COPY . .

RUN pnpm run build

# Stage 2: Run the application
FROM node:20-alpine AS production

COPY --from=builder /app/client /app/client

WORKDIR /app/client

EXPOSE 3000

CMD ["pnpm", "run", "serve"]
