version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client
      - /app/client/node_modules # Exclude node_modules from host mount
    depends_on:
      - server
    environment:
      # Pass environment variables to the client container if needed
      # For example, if client needs to know the server's URL
      VITE_PB_URL: http://server:8080/api
      VITE_RAJAONGKIR_URL: http://server:8080/rajaongkir

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app/server
      - /app/server/node_modules # Exclude node_modules from host mount
    environment:
      # Pass environment variables to the server container if needed
      NODE_ENV: production
