# Stage 1: Build the Vue.js application
FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json ./
COPY client/package.json client/

RUN npm install -g pnpm && \
    pnpm install && \
    pnpm install --prefix client && \

COPY client/ .

RUN pnpm --prefix client run build

# Stage 2: Run the application
FROM node:20-alpine AS production

COPY --from=builder /app/client /app/client

WORKDIR /app/client

EXPOSE 3000

CMD ["pnpm", "run", "serve"]
